#+OPTIONS: tex:t

* Data Pre-Processing
This directory contains all of the data collected from the DJI Tello quadcopter flying in the Bristol Robotics Laboratory.
It also contains the scripts for processing it so that it can be used by the BMNSVGP model.

** Dir Structure
The csv directory contains all of the raw csv files that contain information from the drone and the vicon tracking system. It therefore contains the drones belief in its current position as well as its true position (given by the vicon tracking system). 

** Experiments
The drone was made to follow a trajectory using a closed loop controller with access to the drones true position (vicon data).
A fan was used to simulate turbulence.
We assume the quadcopter lives in a 2D world and simply model the state as $s_t = (x, y)_t$.
We are collecting data for a supervised learning problem where we seek to learn $f$ in,
$$
\Delta s_t = f(s_{t-1}).
$$
The output of the model is the change in state since the last time step i.e. $\Delta s_t = (\Delta x_t, \Delta y_t, \Delta z_t)$, where $\Delta x_t = x_{t} - x_{t-1}$.

** Scripts
- The =parse_cl_data_turbulence.py= script takes a csv file and outputs a npz file containing the inputs and outputs to be used with BMNSVGP.
  - The csv file to read and the npz (numpy) path-to-file should be specified within the script.
- The =visualise_data_turbulence.py= script is a simple script that reads a npz file and plots the quiver and contour of the data.
